### ISSUE TITLE
How can I join the effort/contribute?

### ISSUE THREAD

**Issue by Pritoj** [deeprjs/deepr#3]
Hi,
I've been using GraphQL for a while and have been looking for something like this. TBH I'm just interested in this and want to see how I can be a part of the conversation.

Thanks and good job :) 👏

**Comment by mvila** [comment]
Thanks, @Pritoj for your interest in Deepr.

At this stage of development, I am not sure how you could contribute. Deepr is used internally by [Liaison](https://github.com/liaisonjs/liaison), and the former is intimately correlated to the latter.

Since I'm in the process of finalizing Liaison, major changes are expected in Deepr over the next few months.

Therefore, I would recommend that you wait a little before getting involved.
